services:
  server:
    container_name: flatline-server
    image: flatline-server:0.0.0-dirty-SNAPSHOT
    pull_policy: never # Use local image from the Docker daemon.
    entrypoint:
      - java
      - -server
      # TODO(uoemai): Understand why this next property is not added in Jib.
      - -Dsecrets.bundle.filename=/usr/share/signal/sample-secrets-bundle.yml
      - -Djava.awt.headless=true
      - -Djdk.nio.maxCachedBufferSize=262144
      - -Dlog4j2.formatMsgNoLookups=true
      - -XX:MaxRAMPercentage=75
      - -XX:+HeapDumpOnOutOfMemoryError
      - -XX:HeapDumpPath=/tmp/heapdump.bin
      - -cp
      - "@/app/jib-classpath-file"
      - org.whispersystems.textsecuregcm.WhisperServerService
      - server # TODO(uoemai): Understand why this argument is not added by Jib.
      - /usr/share/signal/sample.yml # TODO(uoemai): Understand why this argument is not added in Jib.
    # Use this section to overwrite configuration files without rebuilding the container image.
    # volumes:
    #   - service/config/sample.yml:/usr/share/signal/sample.yml
    #   - service/config/sample-secrets-bundle.yml:/usr/share/signal/sample-secrets-bundle.yml
  storage-service:
    container_name: flatline-storage-service
    image: flatline-storage-service:0.0.0-dirty-SNAPSHOT-dev
    pull_policy: never # Use local image from the Docker daemon.
    # Use this section to overwrite configuration files without rebuilding the container image.
    # volumes:
    #   - storage-service/src/main/resources/config/dev.yml:/usr/share/signal/dev.yml
