services:
  server:
    container_name: flatline-server
    image: flatline-server:0.0.0-dirty-SNAPSHOT-dev
    pull_policy: never # Only use a local container image.
    # Use this section to overwrite configuration files without rebuilding the container image.
    # volumes:
    #   - service/config/dev.yml:/usr/share/signal/dev.yml
    #   - service/config/sample-secrets-bundle.yml:/usr/share/signal/sample-secrets-bundle.yml
  storage-service:
    container_name: flatline-storage-service
    image: flatline-storage-service:0.0.0-dirty-SNAPSHOT-dev
    pull_policy: never # Only use a local container image.
    # Use this section to overwrite configuration files without rebuilding the container image.
    # volumes:
    #   - storage-service/src/main/resources/config/dev.yml:/usr/share/signal/dev.yml
