services:
  server:
    container_name: flatline-server
    image: flatline-server:0.0.0-dirty-SNAPSHOT-dev
    pull_policy: never # Only use a local container image.
    environment:
      - AWS_REGION=test
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_OVERRIDE=http://flatline-localstack:4566
    # Use this section to overwrite configuration files without rebuilding the container image.
    volumes:
      # - ./service/config/dev.yml:/usr/share/signal/dev.yml
      # - ./service/config/sample-secrets-bundle.yml:/usr/share/signal/sample-secrets-bundle.yml
      - ./dev/noise-tunnel-keystore.p12:/usr/share/signal/noise-tunnel-keystore.p12
    depends_on:
      localstack:
        condition: service_healthy
      redis-cluster:
        condition: service_healthy
      registration-service:
        condition: service_healthy
  storage-service:
    container_name: flatline-storage-service
    image: flatline-storage-service:0.0.0-dirty-SNAPSHOT-dev
    pull_policy: never # Only use a local container image.
    environment:
      - AWS_REGION=test
    # Use this section to overwrite configuration files without rebuilding the container image.
    # volumes:
    #   - storage-service/src/main/resources/config/dev.yml:/usr/share/signal/dev.yml
  registration-service:
    container_name: flatline-registration-service
    image: flatline-registration-service:0.0.0-dirty-SNAPSHOT-dev
    pull_policy: never # Only use a local container image.
    healthcheck:
      test: [ CMD-SHELL, "timeout 1s bash -c '</dev/tcp/localhost/50051' || exit 1" ]
      interval: 2s
      timeout: 1s
      retries: 10
    ports:
      - 50051:50051
  localstack:
    container_name: flatline-localstack
    image: localstack/localstack:4.6.0
    healthcheck:
      test: [ CMD-SHELL, "curl -s localhost:4566/_localstack/init/ready | grep '\"completed\": true'" ]
      interval: 2s
      timeout: 1s
      retries: 10
    ports:
      - 4566:4566
    environment:
      - DISABLE_EVENTS=1
    volumes:
      - dev-localstack-data:/var/lib/localstack
      - ./dev/localstack:/etc/localstack/init/ready.d
      - ./service/config/dynamic/dev.yml:/tmp/dev.yml
  redis-cluster:
    container_name: flatline-redis-cluster
    image: grokzen/redis-cluster:6.2.14
    ports:
      - 7000-7002:7000-7002
    healthcheck:
      test: [ CMD-SHELL, "redis-cli -p 7000 cluster info | grep ^cluster_state:ok" ]
      interval: 2s
      timeout: 1s
      retries: 10
    volumes:
      - dev-redis-data:/redis-data
  tus:
    # Original implementation: https://github.com/signalapp/tus-server
    container_name: flatline-tus
    image: ghcr.io/tus/tusd:v2.8.0
    ports:
      - 8080:8080
    command: []
volumes:
  dev-localstack-data:
  dev-redis-data:
