FROM debian:latest
# Pin dependency versions.
ARG TEMURIN_VER=21.0.7+6
ARG FDB_VER=7.3.63
# Install build and test dependencies.
RUN apt update && apt install -y wget curl docker.io
# Install the Temurin OpenJDK v21.
RUN wget https://github.com/adoptium/temurin21-binaries/releases/download/jdk-${TEMURIN_VER}/OpenJDK21U-jdk_x64_linux_hotspot_$(echo $TEMURIN_VER | tr '+' '_').tar.gz && \
      tar xzf OpenJDK21U-jdk_x64_linux_hotspot_$(echo $TEMURIN_VER | tr '+' '_').tar.gz && \
      mv jdk-${TEMURIN_VER} /opt/
ENV JAVA_HOME=/opt/jdk-${TEMURIN_VER}
ENV PATH=$JAVA_HOME/bin:$PATH
# Install the client for FoundationDB.
RUN wget https://github.com/apple/foundationdb/releases/download/${FDB_VER}/foundationdb-clients_${FDB_VER}-1_amd64.deb && \
      dpkg -i foundationdb-clients_${FDB_VER}-1_amd64.deb
# Copy the source to the container image.
COPY ../ /root/src/
WORKDIR /root/src
