name: Build 

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  whisper-service:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    timeout-minutes: 20

    services:
      foundationdb:
        # Should be the same as the client version or close behind.
        image: foundationdb/foundationdb:7.3.62
        options: --name foundationdb

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK 21
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
        env:
          # Work around incorrect HOME in runners.
          # Source: https://github.com/actions/setup-java/issues/356
          HOME: /root
      - name: Install Docker 
        run: |
          apt update
          apt install -y ca-certificates curl
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          chmod a+r /etc/apt/keyrings/docker.asc
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
            tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt update && apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      - name: Configure FoundationDB
        run: docker exec foundationdb /usr/bin/fdbcli --exec 'configure new single memory'
      - name: Prepare with Maven
        run: |
          ./mvnw -f whisper-service/pom.xml -e -B -Pexclude-spam-filter clean prepare-package -DskipTests=true
          cp whisper-service/service/target/jib-extra/usr/lib/libfdb_c.x86_64.so /usr/lib/libfdb_c.x86_64.so
          ldconfig
      - name: Test & Build
        # Tests for features disabled in the Flatline prototype are excluded.
        run: ./mvnw -f whisper-service/pom.xml -e -B clean verify -DfoundationDb.serviceContainerName=foundationdb -pl '!integration-tests' -Dsurefire.failIfNoSpecifiedTests=false -Dtest=!org.whispersystems.textsecuregcm.controllers.VerificationControllerTest,\!org.whispersystems.textsecuregcm.controllers.SubscriptionControllerTest,\!org.whispersystems.textsecuregcm.registration.IdentityTokenCallCredentialsTest
      - name: Build Container Image
        run: ./mvnw -f whisper-service/pom.xml -e -B clean deploy -Pexclude-spam-filter -Denv=dev -DskipTests
